version: '3'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx
      - nginx-html:/usr/share/nginx/html
    environment:
      ENABLE_IPV6: "true"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - nginx-proxy

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: always
    command: -notify-sighup nginx-proxy -wait 5s:30s -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx:/etc/nginx
      - nginx-html:/usr/share/nginx/html
      - nginx-gen-tmpl:/etc/docker-gen/templates:rw
    links:
      - nginx-proxy
    networks:
      - nginx-proxy

  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.8.1
    container_name: nginx-ssl
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx:/etc/nginx
      - nginx-html:/usr/share/nginx/html
      - nginx-gen-tmpl:/etc/docker-gen/templates:ro
    environment:
      - ACME_CA_URI
      - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"
    links:
      - nginx-proxy
      - nginx-gen
    networks:
      - nginx-proxy

volumes:
  nginx:
  nginx-html:
  nginx-gen-tmpl:

networks:
  nginx-proxy:
    external: true
